sonar.projectKey=ietuday_enterprise-asset-monitoring-platform
sonar.organization=ietuday
sonar.projectName=Enterprise Asset Monitoring Platform

sonar.sources=services,web,scripts
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/vendor/**,**/.venv/**,**/__pycache__/**

sonar.tests=services,web
sonar.test.inclusions=**/*_test.go,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

sonar.sourceEncoding=UTF-8
sonar.coverage.exclusions=services/maintenance-service/main.go,services/maintenance-service/internal/db/db.go

sonar.go.coverage.reportPaths=coverage/go-coverage.out,services/maintenance-service/coverage.out
sonar.python.coverage.reportPaths=services/report-service/coverage.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info,web/dashboard/coverage/lcov.info,services/api-gateway/coverage/lcov.info
