FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o notification-service ./cmd

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/notification-service .

EXPOSE 8090

CMD ["./notification-service"]
